# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db728e86017d220200e80c39392cd89e8cd44f0211d7abec7f322a22828e3cbe8b868be501a55a9bcdcbd7f6855fd508dfec1d0a946a6e04d9c4e748dfea7e9f

test:
  secret_key_base: ca53a833daf03c2c2a1789f5701e9b313c2a00a038973754e84beef9f6f83c8b985a6998e69130458fc6d398d3786108a5623e396af9a7d667df02b9601b19ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["VPS_PRODUCTION_SECRET_KEY_BASE"] %>
